import dynamic from 'next/dynamic'
import { getTranslations } from 'next-intl/server'
import { client } from '@/sanity/lib/client'
import { sanityCache } from '@/sanity/lib/fetch'
import { urlFor } from '@/sanity/lib/image'
import { seriesQuery } from '@/sanity/lib/queries'
import type { SanityImage, Cta } from '@/sanity/lib/types'
import type { PageBySlugQueryResult } from '@/sanity.types'
import SectionAboutPreview from '@/components/about-preview/SectionAboutPreview'
import BoardsPreviewClient from '@/components/boards-preview/BoardsPreviewClient'
import SectionTextImage from '@/components/text-image/SectionTextImage'
import SectionTextGallery from '@/components/text-gallery/SectionTextGallery'
import SectionFullMedia from '@/components/full-media/SectionFullMedia'
import SectionBigQuote from '@/components/big-quote/SectionBigQuote'
import SectionMediaLine from '@/components/media-line/SectionMediaLine'
import SectionFixedImage from '@/components/fixed-image/SectionFixedImage'
import SectionSpecs from '@/components/specs/SectionSpecs'
import type { FeatureItem } from '@/components/features/SectionFeatures'
import type { OutlineMilestone } from '@/components/outline/SectionOutline'
import type { FixedImageItem } from '@/components/fixed-image/SectionFixedImage'

// Lazy-loaded so GSAP only ships on pages that actually render these sections.
const SectionFeatures = dynamic(() => import('@/components/features/SectionFeatures'))
const SectionOutline = dynamic(() => import('@/components/outline/SectionOutline'))
const SectionMarquee = dynamic(() => import('@/components/marquee/SectionMarquee'))

// The exact section shape generated by `pageBySlugQuery` (discriminated on _type).
type Section = NonNullable<NonNullable<PageBySlugQueryResult>['sections']>[number]

// Raw shape returned by `seriesQuery`, before image URLs are resolved.
type RawBoard = {
  _id: string
  name: string
  slug: { current: string }
  style?: string
  mainImage?: SanityImage
}

type RawSeries = {
  _id: string
  name: string
  slug: { current: string }
  tagVariant?: 'dark' | 'amber' | 'cream' | 'red' | 'outline-light' | 'outline-muted'
  boards: RawBoard[]
}

type Props = {
  sections: Section[]
  locale: string
}

/** Normalize a GROQ-projected CTA (nullable fields) to the component `Cta` shape. */
function toCta(c: {
  _key?: string
  text?: string | null
  href?: string | null
  openInNewTab?: boolean | null
}): Cta {
  return {
    _key: c._key,
    text: c.text ?? undefined,
    href: c.href ?? undefined,
    openInNewTab: c.openInNewTab ?? undefined,
  }
}

export default async function PageBuilder({ sections, locale }: Props) {
  if (!sections?.length) return null

  const t = await getTranslations('home')

  // Pre-fetch data only for section types that are actually present
  const needsBoards = sections.some((s) => s._type === 'sectionBoards')
  const rawSeries: RawSeries[] = needsBoards
    ? await client.fetch<RawSeries[]>(seriesQuery, { locale }, sanityCache('series', 'board'))
    : []

  // Pre-resolve image URLs server-side so @sanity/image-url never reaches the client bundle
  const series = rawSeries.map((s) => ({
    ...s,
    boards: s.boards.map((board) => ({
      _id: board._id,
      name: board.name,
      slug: board.slug,
      style: board.style,
      imageUrl: board.mainImage
        ? urlFor(board.mainImage).width(780).height(1218).quality(85).url()
        : undefined,
    })),
  }))

  return (
    <>
      {sections.map((section) => {
        switch (section._type) {
          case 'sectionBoards':
            return (
              <BoardsPreviewClient
                key={section._key}
                series={series}
                title={section.title ?? t('boards_title')}
                discoverCta={t('boards_discover')}
                viewBoardLabel={t('view_board')}
                showFilters={section.showFilters ?? true}
                filterBySeries={section.filterBySeries ?? true}
              />
            )
          case 'sectionAboutPreview':
            return (
              <SectionAboutPreview
                key={section._key}
                eyebrow={section.eyebrow ?? undefined}
                title={section.title ?? undefined}
                image={section.image ?? undefined}
                body={section.body ?? undefined}
                cta={section.cta ? toCta(section.cta) : undefined}
              />
            )
          case 'sectionMarquee':
            return (
              <SectionMarquee
                key={section._key}
                items={section.items ?? []}
              />
            )
          case 'sectionTextImage':
            return (
              <SectionTextImage
                key={section._key}
                label={section.label ?? undefined}
                title={section.title ?? ''}
                body={section.body ?? undefined}
                image={section.image ?? undefined}
                ctas={section.ctas?.map(toCta)}
                theme={section.theme ?? undefined}
                imagePosition={section.imagePosition ?? undefined}
                layout={section.layout ?? undefined}
              />
            )
          case 'sectionTextGallery':
            return (
              <SectionTextGallery
                key={section._key}
                label={section.label ?? undefined}
                title={section.title ?? ''}
                body={section.body ?? undefined}
                gallery={section.gallery ?? []}
                theme={section.theme ?? undefined}
                imagePosition={section.imagePosition ?? undefined}
              />
            )
          case 'sectionFullMedia':
            return (
              <SectionFullMedia
                key={section._key}
                mediaType={section.mediaType ?? undefined}
                size={section.size ?? undefined}
                image={section.image ?? undefined}
                videoUrl={section.videoUrl ?? undefined}
                videoPoster={section.videoPoster ?? undefined}
                videoWidth={section.videoWidth ?? undefined}
                videoHeight={section.videoHeight ?? undefined}
                controls={section.controls ?? undefined}
              />
            )
          case 'sectionBigQuote':
            return (
              <SectionBigQuote
                key={section._key}
                quote={section.quote ?? ''}
                authorName={section.authorName ?? undefined}
                authorRole={section.authorRole ?? undefined}
                theme={section.theme ?? undefined}
              />
            )
          case 'sectionMediaLine':
            return (
              <SectionMediaLine
                key={section._key}
                media={section.media ?? undefined}
                aspectRatio={section.aspectRatio ?? undefined}
                size={section.size ?? undefined}
              />
            )
          case 'sectionFeatures': {
            // Resolve image/poster URLs server-side (component takes plain URLs).
            const featureItems: FeatureItem[] = (section.features ?? []).map((f) => ({
              title: f.title ?? '',
              text: f.text ?? '',
              imageUrl:
                f.mediaType !== 'video' && f.image
                  ? urlFor(f.image).width(900).height(628).quality(85).url()
                  : undefined,
              videoUrl: f.mediaType === 'video' ? (f.videoUrl ?? undefined) : undefined,
              videoPoster:
                f.mediaType === 'video' && f.videoPoster
                  ? urlFor(f.videoPoster).width(900).height(628).quality(85).url()
                  : undefined,
              cta:
                f.cta?.href && f.cta?.text
                  ? { text: f.cta.text, href: f.cta.href, openInNewTab: f.cta.openInNewTab ?? undefined }
                  : undefined,
            }))
            return (
              <SectionFeatures
                key={section._key}
                items={featureItems}
                theme={section.theme === 'dark' ? 'dark' : 'light'}
              />
            )
          }
          case 'sectionOutline': {
            const milestones: OutlineMilestone[] = (section.milestones ?? []).map((m) => ({
              year: m.year ?? '',
              name: m.name ?? '',
              tag: m.tag ?? '',
              svgPath: m.svgPath ?? '',
            }))
            return (
              <SectionOutline
                key={section._key}
                eyebrow={section.eyebrow ?? undefined}
                title={section.title ?? ''}
                intro={section.intro ?? ''}
                milestones={milestones}
                finalImageUrl={section.finalImage ? urlFor(section.finalImage).width(900).quality(85).url() : undefined}
                finalLabel={
                  section.finalLabelTitle
                    ? { title: section.finalLabelTitle, subtitle: section.finalLabelSubtitle ?? '' }
                    : undefined
                }
              />
            )
          }
          case 'sectionFixedImage': {
            const fixedItems: FixedImageItem[] = (section.fixedImages ?? []).map((it) => ({
              _key: it._key,
              imageUrl: it.image ? urlFor(it.image).width(2000).quality(85).url() : undefined,
              title: it.title ?? undefined,
              text: it.text ?? undefined,
              startColumn: it.startColumn ?? undefined,
              verticalPosition: it.verticalPosition ?? undefined,
              cta: it.cta ? toCta(it.cta) : undefined,
            }))
            return <SectionFixedImage key={section._key} items={fixedItems} />
          }
          case 'sectionSpecs':
            return (
              <SectionSpecs
                key={section._key}
                eyebrow={section.eyebrow ?? undefined}
                title={section.title ?? undefined}
                columns={(section.columns ?? []).filter((c): c is string => typeof c === 'string')}
                rows={(section.rows ?? []).map((r) => ({
                  _key: r._key,
                  cells: (r.cells ?? []).map((c) => c ?? ''),
                }))}
              />
            )
          default:
            return null
        }
      })}
    </>
  )
}
