import { getTranslations } from 'next-intl/server'
import { client } from '@/sanity/lib/client'
import { sanityCache } from '@/sanity/lib/fetch'
import { urlFor } from '@/sanity/lib/image'
import { seriesQuery } from '@/sanity/lib/queries'
import type { SanityImage, Cta } from '@/sanity/lib/types'
import type { PageBySlugQueryResult } from '@/sanity.types'
import SectionAboutPreview from '@/components/about-preview/SectionAboutPreview'
import BoardsPreviewClient from '@/components/boards-preview/BoardsPreviewClient'
import SectionMarquee from '@/components/marquee/SectionMarquee'
import SectionTextImage from '@/components/text-image/SectionTextImage'
import SectionTextGallery from '@/components/text-gallery/SectionTextGallery'
import SectionFullMedia from '@/components/full-media/SectionFullMedia'
import SectionBigQuote from '@/components/big-quote/SectionBigQuote'
import SectionMediaLine from '@/components/media-line/SectionMediaLine'

// The exact section shape generated by `pageBySlugQuery` (discriminated on _type).
type Section = NonNullable<NonNullable<PageBySlugQueryResult>['sections']>[number]

// Raw shape returned by `seriesQuery`, before image URLs are resolved.
type RawBoard = {
  _id: string
  name: string
  slug: { current: string }
  style?: string
  mainImage?: SanityImage
}

type RawSeries = {
  _id: string
  name: string
  slug: { current: string }
  tagVariant?: 'dark' | 'amber' | 'cream' | 'red' | 'outline-light' | 'outline-muted'
  boards: RawBoard[]
}

type Props = {
  sections: Section[]
  locale: string
}

/** Normalize a GROQ-projected CTA (nullable fields) to the component `Cta` shape. */
function toCta(c: {
  _key?: string
  text?: string | null
  href?: string | null
  openInNewTab?: boolean | null
}): Cta {
  return {
    _key: c._key,
    text: c.text ?? undefined,
    href: c.href ?? undefined,
    openInNewTab: c.openInNewTab ?? undefined,
  }
}

export default async function PageBuilder({ sections, locale }: Props) {
  if (!sections?.length) return null

  const t = await getTranslations('home')

  // Pre-fetch data only for section types that are actually present
  const needsBoards = sections.some((s) => s._type === 'sectionBoards')
  const rawSeries: RawSeries[] = needsBoards
    ? await client.fetch<RawSeries[]>(seriesQuery, { locale }, sanityCache('series', 'board'))
    : []

  // Pre-resolve image URLs server-side so @sanity/image-url never reaches the client bundle
  const series = rawSeries.map((s) => ({
    ...s,
    boards: s.boards.map((board) => ({
      _id: board._id,
      name: board.name,
      slug: board.slug,
      style: board.style,
      imageUrl: board.mainImage
        ? urlFor(board.mainImage).width(780).height(1218).quality(85).url()
        : undefined,
    })),
  }))

  return (
    <>
      {sections.map((section) => {
        switch (section._type) {
          case 'sectionBoards':
            return (
              <BoardsPreviewClient
                key={section._key}
                series={series}
                title={section.title ?? t('boards_title')}
                discoverCta={t('boards_discover')}
                viewBoardLabel={t('view_board')}
                showFilters={section.showFilters ?? true}
              />
            )
          case 'sectionAboutPreview':
            return (
              <SectionAboutPreview
                key={section._key}
                eyebrow={section.eyebrow ?? undefined}
                title={section.title ?? undefined}
                image={section.image ?? undefined}
                body={section.body ?? undefined}
                cta={section.cta ? toCta(section.cta) : undefined}
              />
            )
          case 'sectionMarquee':
            return (
              <SectionMarquee
                key={section._key}
                items={section.items ?? []}
              />
            )
          case 'sectionTextImage':
            return (
              <SectionTextImage
                key={section._key}
                label={section.label ?? undefined}
                title={section.title ?? ''}
                body={section.body ?? undefined}
                image={section.image ?? undefined}
                ctas={section.ctas?.map(toCta)}
                theme={section.theme ?? undefined}
                imagePosition={section.imagePosition ?? undefined}
                layout={section.layout ?? undefined}
              />
            )
          case 'sectionTextGallery':
            return (
              <SectionTextGallery
                key={section._key}
                label={section.label ?? undefined}
                title={section.title ?? ''}
                body={section.body ?? undefined}
                gallery={section.gallery ?? []}
                theme={section.theme ?? undefined}
                imagePosition={section.imagePosition ?? undefined}
              />
            )
          case 'sectionFullMedia':
            return (
              <SectionFullMedia
                key={section._key}
                mediaType={section.mediaType ?? undefined}
                size={section.size ?? undefined}
                image={section.image ?? undefined}
                videoUrl={section.videoUrl ?? undefined}
                videoPoster={section.videoPoster ?? undefined}
                videoWidth={section.videoWidth ?? undefined}
                videoHeight={section.videoHeight ?? undefined}
                controls={section.controls ?? undefined}
              />
            )
          case 'sectionBigQuote':
            return (
              <SectionBigQuote
                key={section._key}
                quote={section.quote ?? ''}
                authorName={section.authorName ?? undefined}
                authorRole={section.authorRole ?? undefined}
                theme={section.theme ?? undefined}
              />
            )
          case 'sectionMediaLine':
            return (
              <SectionMediaLine
                key={section._key}
                media={section.media ?? undefined}
                aspectRatio={section.aspectRatio ?? undefined}
                size={section.size ?? undefined}
              />
            )
          default:
            return null
        }
      })}
    </>
  )
}
