/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type MediaItemImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "mediaItem.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  _type: "image";
};

export type VideoPoster = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "mediaItem.videoPoster.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type SectionMediaLine = {
  _type: "sectionMediaLine";
  media?: Array<{
    mediaType?: "image" | "video";
    image?: MediaItemImage;
    videoUrl?: string;
    videoPoster?: VideoPoster;
    controls?: boolean;
    _type: "mediaItem";
    _key: string;
  }>;
  aspectRatio?: "4 / 3" | "3 / 2" | "1 / 1" | "4 / 5" | "16 / 9";
  size?: "in-grid" | "full";
};

export type SectionBigQuote = {
  _type: "sectionBigQuote";
  quote: string;
  authorName?: string;
  authorRole?: string;
  theme?: "dark" | "light";
};

export type SectionFullMedia = {
  _type: "sectionFullMedia";
  mediaType?: "image" | "video";
  size?: "full" | "in-grid";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  videoUrl?: string;
  videoPoster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  videoWidth?: number;
  videoHeight?: number;
  controls?: boolean;
};

export type SectionTextGallery = {
  _type: "sectionTextGallery";
  label?: string;
  title: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  }>;
  theme?: "light" | "dark";
  imagePosition?: "left" | "right";
};

export type SectionTextImage = {
  _type: "sectionTextImage";
  layout?: "full" | "contained";
  label?: string;
  title: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ctas?: Array<
    {
      _key: string;
    } & Link
  >;
  theme?: "light" | "dark";
  imagePosition?: "left" | "right";
};

export type SectionMarquee = {
  _type: "sectionMarquee";
  items?: Array<{
    text?: string;
    accent?: boolean;
    _key: string;
  }>;
};

export type SectionBoards = {
  _type: "sectionBoards";
  title?: string;
  showFilters?: boolean;
};

export type SectionAboutPreview = {
  _type: "sectionAboutPreview";
  eyebrow?: string;
  title?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  cta?: Link;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandName: string;
  siteTitle: string;
  seoDescription: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  contact?: {
    email?: string;
    phone?: string;
    address?: string;
  };
  social?: {
    facebook?: string;
    google?: string;
    instagram?: string;
    linkedin?: string;
    messenger?: string;
    tiktok?: string;
    whatsapp?: string;
    x?: string;
    youtube?: string;
  };
  footer?: {
    copyright?: string;
    privacyPolicyUrl?: Slug;
    cookiePolicyUrl?: Slug;
  };
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type BoardsPageSettings = {
  _id: string;
  _type: "boardsPageSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: InternationalizedArrayString;
  seoDescription?: InternationalizedArrayText;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type InternationalizedArrayText = Array<
  {
    _key: string;
  } & InternationalizedArrayTextValue
>;

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type AccessoriesPageSettings = {
  _id: string;
  _type: "accessoriesPageSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: InternationalizedArrayString;
  seoDescription?: InternationalizedArrayText;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
  language: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
  language: string;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type BoardReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "board";
};

export type AccessoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "accessory";
};

export type NavigationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "navigation";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?:
    | PageReference
    | BoardReference
    | AccessoryReference
    | NavigationReference;
  language: string;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  items?: Array<{
    label: string;
    internalLink?: PageReference;
    externalUrl?: string;
    openInNewTab?: boolean;
    _type: "navItem";
    _key: string;
  }>;
  language: string;
};

export type AccessoryCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "accessoryCategory";
};

export type Accessory = {
  _id: string;
  _type: "accessory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  category?: AccessoryCategoryReference;
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  specifications?: Array<{
    name?: string;
    value?: string;
    _key: string;
  }>;
  sizes?: Array<string>;
  price?: number;
  originalPrice?: number;
  currency?: "EUR" | "USD" | "GBP";
  order?: number;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  language: string;
};

export type AccessoryCategory = {
  _id: string;
  _type: "accessoryCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: InternationalizedArrayString;
  slug: Slug;
  order?: number;
};

export type SeriesReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "series";
};

export type Board = {
  _id: string;
  _type: "board";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  series: SeriesReference;
  heroTitle?: string;
  heroTagline?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  presentationTitle?: string;
  presentationText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  presentationNumbers?: Array<{
    value: string;
    unit?: string;
    label: string;
    _key: string;
  }>;
  presentationTags?: Array<{
    text: string;
    style?:
      | "cream"
      | "dark"
      | "amber"
      | "red"
      | "outline-light"
      | "outline-muted";
    _key: string;
  }>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  }>;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  style?: string;
  sections?: Array<
    | ({
        _key: string;
      } & SectionAboutPreview)
    | ({
        _key: string;
      } & SectionBoards)
    | ({
        _key: string;
      } & SectionMarquee)
    | ({
        _key: string;
      } & SectionTextImage)
    | ({
        _key: string;
      } & SectionTextGallery)
    | ({
        _key: string;
      } & SectionFullMedia)
    | ({
        _key: string;
      } & SectionBigQuote)
    | ({
        _key: string;
      } & SectionMediaLine)
  >;
  weight?: number;
  price?: number;
  currency?: "EUR" | "USD" | "GBP";
  order?: number;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  language: string;
};

export type Series = {
  _id: string;
  _type: "series";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: InternationalizedArrayString;
  slug: Slug;
  tagVariant?:
    | "dark"
    | "amber"
    | "cream"
    | "red"
    | "outline-light"
    | "outline-muted";
  order?: number;
};

export type Link = {
  _type: "link";
  text?: string;
  type: string;
  internalLink?: PageReference;
  url?: string;
  email?: string;
  phone?: string;
  value?: string;
  blank?: boolean;
  parameters?: string;
  anchor?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroTitle?: string;
  heroSubtitle?: string;
  sections?: Array<
    | ({
        _key: string;
      } & SectionAboutPreview)
    | ({
        _key: string;
      } & SectionBoards)
    | ({
        _key: string;
      } & SectionMarquee)
    | ({
        _key: string;
      } & SectionTextImage)
    | ({
        _key: string;
      } & SectionTextGallery)
    | ({
        _key: string;
      } & SectionFullMedia)
    | ({
        _key: string;
      } & SectionBigQuote)
    | ({
        _key: string;
      } & SectionMediaLine)
  >;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  language: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | MediaItemImage
  | VideoPoster
  | SectionMediaLine
  | SectionBigQuote
  | SectionFullMedia
  | SectionTextGallery
  | SectionTextImage
  | SectionMarquee
  | SectionBoards
  | SectionAboutPreview
  | SiteSettings
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | BoardsPageSettings
  | InternationalizedArrayText
  | InternationalizedArrayString
  | AccessoriesPageSettings
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | TranslationMetadata
  | InternationalizedArrayReference
  | PageReference
  | BoardReference
  | AccessoryReference
  | NavigationReference
  | InternationalizedArrayReferenceValue
  | Navigation
  | AccessoryCategoryReference
  | Accessory
  | AccessoryCategory
  | SeriesReference
  | Board
  | Series
  | Link
  | Page
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: boardsQuery
// Query: *[_type == "board" && language == $locale && !(_id in path("drafts.**"))] | order(order asc) {    _id,    name,    slug,    series->{ _id, "name": coalesce(name[language == $locale][0].value, name[language == "en"][0].value, name[0].value), slug },    style,    weight,    mainImage  }
export type BoardsQueryResult = Array<{
  _id: string;
  name: string;
  slug: Slug;
  series: {
    _id: string;
    name: string | null;
    slug: Slug;
  };
  style: string | null;
  weight: number | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: boardBySlugQuery
// Query: *[_type == "board" && slug.current == $slug && language == $locale && !(_id in path("drafts.**"))][0] {    _id,    name,    slug,    series->{ _id, "name": coalesce(name[language == $locale][0].value, name[language == "en"][0].value, name[0].value), slug },    heroTitle,    heroTagline,    heroImage,    presentationTitle,    presentationText,    presentationNumbers[]{ value, unit, label },    presentationTags[]{ text, style },    gallery[]{      asset,      alt,      hotspot,      crop    },    mainImage,    style,    weight,    price,    currency,    sections[] {      _type,      _key,      title,      showFilters,      items,      eyebrow,      label,      body,      image,      gallery,      mediaType,      size,      aspectRatio,      media,      videoUrl,      videoPoster,      videoWidth,      videoHeight,      controls,      imagePosition,      layout,      theme,      quote,      authorName,      authorRole,      "cta": cta {        "text": text,        "openInNewTab": openInNewTab,        "href": select(          type == "internal" => "/" + internalLink->slug.current,          type == "external" => url,          type == "email" => "mailto:" + email,          type == "phone" => "tel:" + phone        )      },      "ctas": ctas[] {        _key,        "text": text,        "openInNewTab": openInNewTab,        "href": select(          type == "internal" => "/" + internalLink->slug.current,          type == "external" => url,          type == "email" => "mailto:" + email,          type == "phone" => "tel:" + phone        )      }    },    seoTitle,    seoDescription,    ogImage,    "translations": *[_type == "translation.metadata" && references(^._id)][0].translations[]{      "lang": value->language,      "slug": value->slug.current    }  }
export type BoardBySlugQueryResult = {
  _id: string;
  name: string;
  slug: Slug;
  series: {
    _id: string;
    name: string | null;
    slug: Slug;
  };
  heroTitle: string | null;
  heroTagline: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  presentationTitle: string | null;
  presentationText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  presentationNumbers: Array<{
    value: string;
    unit: string | null;
    label: string;
  }> | null;
  presentationTags: Array<{
    text: string;
    style:
      | "amber"
      | "cream"
      | "dark"
      | "outline-light"
      | "outline-muted"
      | "red"
      | null;
  }> | null;
  gallery: Array<{
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  style: string | null;
  weight: number | null;
  price: number | null;
  currency: "EUR" | "GBP" | "USD" | null;
  sections: Array<
    | {
        _type: "sectionAboutPreview";
        _key: string;
        title: string | null;
        showFilters: null;
        items: null;
        eyebrow: string | null;
        label: null;
        body: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        gallery: null;
        mediaType: null;
        size: null;
        aspectRatio: null;
        media: null;
        videoUrl: null;
        videoPoster: null;
        videoWidth: null;
        videoHeight: null;
        controls: null;
        imagePosition: null;
        layout: null;
        theme: null;
        quote: null;
        authorName: null;
        authorRole: null;
        cta: {
          text: string | null;
          openInNewTab: null;
          href: string | null;
        } | null;
        ctas: null;
      }
    | {
        _type: "sectionBigQuote";
        _key: string;
        title: null;
        showFilters: null;
        items: null;
        eyebrow: null;
        label: null;
        body: null;
        image: null;
        gallery: null;
        mediaType: null;
        size: null;
        aspectRatio: null;
        media: null;
        videoUrl: null;
        videoPoster: null;
        videoWidth: null;
        videoHeight: null;
        controls: null;
        imagePosition: null;
        layout: null;
        theme: "dark" | "light" | null;
        quote: string;
        authorName: string | null;
        authorRole: string | null;
        cta: null;
        ctas: null;
      }
    | {
        _type: "sectionBoards";
        _key: string;
        title: string | null;
        showFilters: boolean | null;
        items: null;
        eyebrow: null;
        label: null;
        body: null;
        image: null;
        gallery: null;
        mediaType: null;
        size: null;
        aspectRatio: null;
        media: null;
        videoUrl: null;
        videoPoster: null;
        videoWidth: null;
        videoHeight: null;
        controls: null;
        imagePosition: null;
        layout: null;
        theme: null;
        quote: null;
        authorName: null;
        authorRole: null;
        cta: null;
        ctas: null;
      }
    | {
        _type: "sectionFullMedia";
        _key: string;
        title: null;
        showFilters: null;
        items: null;
        eyebrow: null;
        label: null;
        body: null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        } | null;
        gallery: null;
        mediaType: "image" | "video" | null;
        size: "full" | "in-grid" | null;
        aspectRatio: null;
        media: null;
        videoUrl: string | null;
        videoPoster: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        videoWidth: number | null;
        videoHeight: number | null;
        controls: boolean | null;
        imagePosition: null;
        layout: null;
        theme: null;
        quote: null;
        authorName: null;
        authorRole: null;
        cta: null;
        ctas: null;
      }
    | {
        _type: "sectionMarquee";
        _key: string;
        title: null;
        showFilters: null;
        items: Array<{
          text?: string;
          accent?: boolean;
          _key: string;
        }> | null;
        eyebrow: null;
        label: null;
        body: null;
        image: null;
        gallery: null;
        mediaType: null;
        size: null;
        aspectRatio: null;
        media: null;
        videoUrl: null;
        videoPoster: null;
        videoWidth: null;
        videoHeight: null;
        controls: null;
        imagePosition: null;
        layout: null;
        theme: null;
        quote: null;
        authorName: null;
        authorRole: null;
        cta: null;
        ctas: null;
      }
    | {
        _type: "sectionMediaLine";
        _key: string;
        title: null;
        showFilters: null;
        items: null;
        eyebrow: null;
        label: null;
        body: null;
        image: null;
        gallery: null;
        mediaType: null;
        size: "full" | "in-grid" | null;
        aspectRatio: "1 / 1" | "16 / 9" | "3 / 2" | "4 / 3" | "4 / 5" | null;
        media: Array<{
          mediaType?: "image" | "video";
          image?: MediaItemImage;
          videoUrl?: string;
          videoPoster?: VideoPoster;
          controls?: boolean;
          _type: "mediaItem";
          _key: string;
        }> | null;
        videoUrl: null;
        videoPoster: null;
        videoWidth: null;
        videoHeight: null;
        controls: null;
        imagePosition: null;
        layout: null;
        theme: null;
        quote: null;
        authorName: null;
        authorRole: null;
        cta: null;
        ctas: null;
      }
    | {
        _type: "sectionTextGallery";
        _key: string;
        title: string;
        showFilters: null;
        items: null;
        eyebrow: null;
        label: string | null;
        body: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "blockquote"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        image: null;
        gallery: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
          _key: string;
        }> | null;
        mediaType: null;
        size: null;
        aspectRatio: null;
        media: null;
        videoUrl: null;
        videoPoster: null;
        videoWidth: null;
        videoHeight: null;
        controls: null;
        imagePosition: "left" | "right" | null;
        layout: null;
        theme: "dark" | "light" | null;
        quote: null;
        authorName: null;
        authorRole: null;
        cta: null;
        ctas: null;
      }
    | {
        _type: "sectionTextImage";
        _key: string;
        title: string;
        showFilters: null;
        items: null;
        eyebrow: null;
        label: string | null;
        body: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "blockquote"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        gallery: null;
        mediaType: null;
        size: null;
        aspectRatio: null;
        media: null;
        videoUrl: null;
        videoPoster: null;
        videoWidth: null;
        videoHeight: null;
        controls: null;
        imagePosition: "left" | "right" | null;
        layout: "contained" | "full" | null;
        theme: "dark" | "light" | null;
        quote: null;
        authorName: null;
        authorRole: null;
        cta: null;
        ctas: Array<{
          _key: string;
          text: string | null;
          openInNewTab: null;
          href: string | null;
        }> | null;
      }
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  translations: Array<{
    lang: string | null;
    slug: string | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: seriesQuery
// Query: *[_type == "series" && !(_id in path("drafts.**"))] | order(_createdAt asc) {    _id,    "name": coalesce(      name[language == $locale][0].value,      name[language == "en"][0].value,      name[0].value    ),    slug,    tagVariant,    "boards": *[_type == "board" && !(_id in path("drafts.**")) && language == $locale && references(^._id)] | order(order asc) {      _id,      name,      slug,      style,      mainImage    }  }[count(boards) > 0]
export type SeriesQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug;
  tagVariant:
    | "amber"
    | "cream"
    | "dark"
    | "outline-light"
    | "outline-muted"
    | "red"
    | null;
  boards: Array<{
    _id: string;
    name: string;
    slug: Slug;
    style: string | null;
    mainImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    } | null;
  }>;
}>;

// Source: sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0] {    brandName,    siteTitle,    seoDescription,    logo,    ogImage,    contact,    social,    footer  }
export type SiteSettingsQueryResult = {
  brandName: string;
  siteTitle: string;
  seoDescription: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  contact: {
    email?: string;
    phone?: string;
    address?: string;
  } | null;
  social: {
    facebook?: string;
    google?: string;
    instagram?: string;
    linkedin?: string;
    messenger?: string;
    tiktok?: string;
    whatsapp?: string;
    x?: string;
    youtube?: string;
  } | null;
  footer: {
    copyright?: string;
    privacyPolicyUrl?: Slug;
    cookiePolicyUrl?: Slug;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: boardsPageSettingsQuery
// Query: *[_type == "boardsPageSettings" && _id == "boardsPageSettings"][0] {    "seoTitle": coalesce(      seoTitle[language == $locale][0].value,      seoTitle[language == "en"][0].value,      seoTitle[0].value    ),    "seoDescription": coalesce(      seoDescription[language == $locale][0].value,      seoDescription[language == "en"][0].value,      seoDescription[0].value    ),    ogImage  }
export type BoardsPageSettingsQueryResult = {
  seoTitle: string | null;
  seoDescription: string | null;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: sitemapBoardsQuery
// Query: *[_type == "board" && defined(slug.current) && !(_id in path("drafts.**"))] | order(_updatedAt desc) {    "slug": slug.current,    language,    _updatedAt,    "translations": *[_type == "translation.metadata" && references(^._id)][0].translations[]{      "lang": value->language,      "slug": value->slug.current    }  }
export type SitemapBoardsQueryResult = Array<{
  slug: string;
  language: string;
  _updatedAt: string;
  translations: Array<{
    lang: string | null;
    slug: string | null;
  }> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: sitemapHomePagesQuery
// Query: *[_type == "page" && slug.current == "home" && !(_id in path("drafts.**"))] {    language,    _updatedAt  }
export type SitemapHomePagesQueryResult = Array<{
  language: string;
  _updatedAt: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: navigationQuery
// Query: *[_type == "navigation" && title == $title && language == $locale][0] {    items[] {      label,      openInNewTab,      "slug": internalLink->slug.current,      "externalUrl": externalUrl,    }  }
export type NavigationQueryResult = {
  items: Array<{
    label: string;
    openInNewTab: boolean | null;
    slug: string | null;
    externalUrl: string | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: footerSeriesQuery
// Query: *[_type == "series" && !(_id in path("drafts.**"))] | order(_createdAt asc) [0..1] {    _id,    "name": coalesce(      name[language == $locale][0].value,      name[language == "en"][0].value,      name[0].value    ),    "boards": *[_type == "board" && !(_id in path("drafts.**")) && language == $locale && references(^._id)] | order(order asc) {      _id,      name,      slug    }  }
export type FooterSeriesQueryResult = Array<{
  _id: string;
  name: string | null;
  boards: Array<{
    _id: string;
    name: string;
    slug: Slug;
  }>;
}>;

// Source: sanity/lib/queries.ts
// Variable: pageBySlugQuery
// Query: coalesce(    *[_type == "page" && slug.current == $slug && language == $locale][0],    *[_type == "page" && slug.current == $slug && language == "fr"][0]  ) {    _id,    title,    heroImage,    heroTitle,    "heroSubtitle": coalesce(heroSubtitle[language == $locale][0].value, heroSubtitle[0].value, heroSubtitle),    slug,    seoTitle,    seoDescription,    ogImage,    sections[] {      _type,      _key,      title,      showFilters,      items,      eyebrow,      label,      body,      image,      gallery,      mediaType,      size,      aspectRatio,      media,      videoUrl,      videoPoster,      videoWidth,      videoHeight,      controls,      imagePosition,      layout,      theme,      quote,      authorName,      authorRole,      "cta": cta {        "text": text,        "openInNewTab": openInNewTab,        "href": select(          type == "internal" => "/" + internalLink->slug.current,          type == "external" => url,          type == "email" => "mailto:" + email,          type == "phone" => "tel:" + phone        )      },      "ctas": ctas[] {        _key,        "text": text,        "openInNewTab": openInNewTab,        "href": select(          type == "internal" => "/" + internalLink->slug.current,          type == "external" => url,          type == "email" => "mailto:" + email,          type == "phone" => "tel:" + phone        )      }    }  }
export type PageBySlugQueryResult = {
  _id: string;
  title: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  heroTitle: string | null;
  heroSubtitle: string | null;
  slug: Slug;
  seoTitle: string | null;
  seoDescription: string | null;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  sections: Array<
    | {
        _type: "sectionAboutPreview";
        _key: string;
        title: string | null;
        showFilters: null;
        items: null;
        eyebrow: string | null;
        label: null;
        body: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        gallery: null;
        mediaType: null;
        size: null;
        aspectRatio: null;
        media: null;
        videoUrl: null;
        videoPoster: null;
        videoWidth: null;
        videoHeight: null;
        controls: null;
        imagePosition: null;
        layout: null;
        theme: null;
        quote: null;
        authorName: null;
        authorRole: null;
        cta: {
          text: string | null;
          openInNewTab: null;
          href: string | null;
        } | null;
        ctas: null;
      }
    | {
        _type: "sectionBigQuote";
        _key: string;
        title: null;
        showFilters: null;
        items: null;
        eyebrow: null;
        label: null;
        body: null;
        image: null;
        gallery: null;
        mediaType: null;
        size: null;
        aspectRatio: null;
        media: null;
        videoUrl: null;
        videoPoster: null;
        videoWidth: null;
        videoHeight: null;
        controls: null;
        imagePosition: null;
        layout: null;
        theme: "dark" | "light" | null;
        quote: string;
        authorName: string | null;
        authorRole: string | null;
        cta: null;
        ctas: null;
      }
    | {
        _type: "sectionBoards";
        _key: string;
        title: string | null;
        showFilters: boolean | null;
        items: null;
        eyebrow: null;
        label: null;
        body: null;
        image: null;
        gallery: null;
        mediaType: null;
        size: null;
        aspectRatio: null;
        media: null;
        videoUrl: null;
        videoPoster: null;
        videoWidth: null;
        videoHeight: null;
        controls: null;
        imagePosition: null;
        layout: null;
        theme: null;
        quote: null;
        authorName: null;
        authorRole: null;
        cta: null;
        ctas: null;
      }
    | {
        _type: "sectionFullMedia";
        _key: string;
        title: null;
        showFilters: null;
        items: null;
        eyebrow: null;
        label: null;
        body: null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        } | null;
        gallery: null;
        mediaType: "image" | "video" | null;
        size: "full" | "in-grid" | null;
        aspectRatio: null;
        media: null;
        videoUrl: string | null;
        videoPoster: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        videoWidth: number | null;
        videoHeight: number | null;
        controls: boolean | null;
        imagePosition: null;
        layout: null;
        theme: null;
        quote: null;
        authorName: null;
        authorRole: null;
        cta: null;
        ctas: null;
      }
    | {
        _type: "sectionMarquee";
        _key: string;
        title: null;
        showFilters: null;
        items: Array<{
          text?: string;
          accent?: boolean;
          _key: string;
        }> | null;
        eyebrow: null;
        label: null;
        body: null;
        image: null;
        gallery: null;
        mediaType: null;
        size: null;
        aspectRatio: null;
        media: null;
        videoUrl: null;
        videoPoster: null;
        videoWidth: null;
        videoHeight: null;
        controls: null;
        imagePosition: null;
        layout: null;
        theme: null;
        quote: null;
        authorName: null;
        authorRole: null;
        cta: null;
        ctas: null;
      }
    | {
        _type: "sectionMediaLine";
        _key: string;
        title: null;
        showFilters: null;
        items: null;
        eyebrow: null;
        label: null;
        body: null;
        image: null;
        gallery: null;
        mediaType: null;
        size: "full" | "in-grid" | null;
        aspectRatio: "1 / 1" | "16 / 9" | "3 / 2" | "4 / 3" | "4 / 5" | null;
        media: Array<{
          mediaType?: "image" | "video";
          image?: MediaItemImage;
          videoUrl?: string;
          videoPoster?: VideoPoster;
          controls?: boolean;
          _type: "mediaItem";
          _key: string;
        }> | null;
        videoUrl: null;
        videoPoster: null;
        videoWidth: null;
        videoHeight: null;
        controls: null;
        imagePosition: null;
        layout: null;
        theme: null;
        quote: null;
        authorName: null;
        authorRole: null;
        cta: null;
        ctas: null;
      }
    | {
        _type: "sectionTextGallery";
        _key: string;
        title: string;
        showFilters: null;
        items: null;
        eyebrow: null;
        label: string | null;
        body: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "blockquote"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        image: null;
        gallery: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
          _key: string;
        }> | null;
        mediaType: null;
        size: null;
        aspectRatio: null;
        media: null;
        videoUrl: null;
        videoPoster: null;
        videoWidth: null;
        videoHeight: null;
        controls: null;
        imagePosition: "left" | "right" | null;
        layout: null;
        theme: "dark" | "light" | null;
        quote: null;
        authorName: null;
        authorRole: null;
        cta: null;
        ctas: null;
      }
    | {
        _type: "sectionTextImage";
        _key: string;
        title: string;
        showFilters: null;
        items: null;
        eyebrow: null;
        label: string | null;
        body: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "blockquote"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        gallery: null;
        mediaType: null;
        size: null;
        aspectRatio: null;
        media: null;
        videoUrl: null;
        videoPoster: null;
        videoWidth: null;
        videoHeight: null;
        controls: null;
        imagePosition: "left" | "right" | null;
        layout: "contained" | "full" | null;
        theme: "dark" | "light" | null;
        quote: null;
        authorName: null;
        authorRole: null;
        cta: null;
        ctas: Array<{
          _key: string;
          text: string | null;
          openInNewTab: null;
          href: string | null;
        }> | null;
      }
  > | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "board" && language == $locale && !(_id in path("drafts.**"))] | order(order asc) {\n    _id,\n    name,\n    slug,\n    series->{ _id, "name": coalesce(name[language == $locale][0].value, name[language == "en"][0].value, name[0].value), slug },\n    style,\n    weight,\n    mainImage\n  }\n': BoardsQueryResult;
    '\n  *[_type == "board" && slug.current == $slug && language == $locale && !(_id in path("drafts.**"))][0] {\n    _id,\n    name,\n    slug,\n    series->{ _id, "name": coalesce(name[language == $locale][0].value, name[language == "en"][0].value, name[0].value), slug },\n    heroTitle,\n    heroTagline,\n    heroImage,\n    presentationTitle,\n    presentationText,\n    presentationNumbers[]{ value, unit, label },\n    presentationTags[]{ text, style },\n    gallery[]{\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n    mainImage,\n    style,\n    weight,\n    price,\n    currency,\n    sections[] {\n      _type,\n      _key,\n      title,\n      showFilters,\n      items,\n      eyebrow,\n      label,\n      body,\n      image,\n      gallery,\n      mediaType,\n      size,\n      aspectRatio,\n      media,\n      videoUrl,\n      videoPoster,\n      videoWidth,\n      videoHeight,\n      controls,\n      imagePosition,\n      layout,\n      theme,\n      quote,\n      authorName,\n      authorRole,\n      "cta": cta {\n        "text": text,\n        "openInNewTab": openInNewTab,\n        "href": select(\n          type == "internal" => "/" + internalLink->slug.current,\n          type == "external" => url,\n          type == "email" => "mailto:" + email,\n          type == "phone" => "tel:" + phone\n        )\n      },\n      "ctas": ctas[] {\n        _key,\n        "text": text,\n        "openInNewTab": openInNewTab,\n        "href": select(\n          type == "internal" => "/" + internalLink->slug.current,\n          type == "external" => url,\n          type == "email" => "mailto:" + email,\n          type == "phone" => "tel:" + phone\n        )\n      }\n    },\n    seoTitle,\n    seoDescription,\n    ogImage,\n    "translations": *[_type == "translation.metadata" && references(^._id)][0].translations[]{\n      "lang": value->language,\n      "slug": value->slug.current\n    }\n  }\n': BoardBySlugQueryResult;
    '\n  *[_type == "series" && !(_id in path("drafts.**"))] | order(_createdAt asc) {\n    _id,\n    "name": coalesce(\n      name[language == $locale][0].value,\n      name[language == "en"][0].value,\n      name[0].value\n    ),\n    slug,\n    tagVariant,\n    "boards": *[_type == "board" && !(_id in path("drafts.**")) && language == $locale && references(^._id)] | order(order asc) {\n      _id,\n      name,\n      slug,\n      style,\n      mainImage\n    }\n  }[count(boards) > 0]\n': SeriesQueryResult;
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0] {\n    brandName,\n    siteTitle,\n    seoDescription,\n    logo,\n    ogImage,\n    contact,\n    social,\n    footer\n  }\n': SiteSettingsQueryResult;
    '\n  *[_type == "boardsPageSettings" && _id == "boardsPageSettings"][0] {\n    "seoTitle": coalesce(\n      seoTitle[language == $locale][0].value,\n      seoTitle[language == "en"][0].value,\n      seoTitle[0].value\n    ),\n    "seoDescription": coalesce(\n      seoDescription[language == $locale][0].value,\n      seoDescription[language == "en"][0].value,\n      seoDescription[0].value\n    ),\n    ogImage\n  }\n': BoardsPageSettingsQueryResult;
    '\n  *[_type == "board" && defined(slug.current) && !(_id in path("drafts.**"))] | order(_updatedAt desc) {\n    "slug": slug.current,\n    language,\n    _updatedAt,\n    "translations": *[_type == "translation.metadata" && references(^._id)][0].translations[]{\n      "lang": value->language,\n      "slug": value->slug.current\n    }\n  }\n': SitemapBoardsQueryResult;
    '\n  *[_type == "page" && slug.current == "home" && !(_id in path("drafts.**"))] {\n    language,\n    _updatedAt\n  }\n': SitemapHomePagesQueryResult;
    '\n  *[_type == "navigation" && title == $title && language == $locale][0] {\n    items[] {\n      label,\n      openInNewTab,\n      "slug": internalLink->slug.current,\n      "externalUrl": externalUrl,\n    }\n  }\n': NavigationQueryResult;
    '\n  *[_type == "series" && !(_id in path("drafts.**"))] | order(_createdAt asc) [0..1] {\n    _id,\n    "name": coalesce(\n      name[language == $locale][0].value,\n      name[language == "en"][0].value,\n      name[0].value\n    ),\n    "boards": *[_type == "board" && !(_id in path("drafts.**")) && language == $locale && references(^._id)] | order(order asc) {\n      _id,\n      name,\n      slug\n    }\n  }\n': FooterSeriesQueryResult;
    '\n  coalesce(\n    *[_type == "page" && slug.current == $slug && language == $locale][0],\n    *[_type == "page" && slug.current == $slug && language == "fr"][0]\n  ) {\n    _id,\n    title,\n    heroImage,\n    heroTitle,\n    "heroSubtitle": coalesce(heroSubtitle[language == $locale][0].value, heroSubtitle[0].value, heroSubtitle),\n    slug,\n    seoTitle,\n    seoDescription,\n    ogImage,\n    sections[] {\n      _type,\n      _key,\n      title,\n      showFilters,\n      items,\n      eyebrow,\n      label,\n      body,\n      image,\n      gallery,\n      mediaType,\n      size,\n      aspectRatio,\n      media,\n      videoUrl,\n      videoPoster,\n      videoWidth,\n      videoHeight,\n      controls,\n      imagePosition,\n      layout,\n      theme,\n      quote,\n      authorName,\n      authorRole,\n      "cta": cta {\n        "text": text,\n        "openInNewTab": openInNewTab,\n        "href": select(\n          type == "internal" => "/" + internalLink->slug.current,\n          type == "external" => url,\n          type == "email" => "mailto:" + email,\n          type == "phone" => "tel:" + phone\n        )\n      },\n      "ctas": ctas[] {\n        _key,\n        "text": text,\n        "openInNewTab": openInNewTab,\n        "href": select(\n          type == "internal" => "/" + internalLink->slug.current,\n          type == "external" => url,\n          type == "email" => "mailto:" + email,\n          type == "phone" => "tel:" + phone\n        )\n      }\n    }\n  }\n': PageBySlugQueryResult;
  }
}
