import { accessory } from './documents/accessory'
import { accessoryCategory } from './documents/accessoryCategory'
import { accessoriesPageSettings } from './documents/accessoriesPageSettings'
import { board } from './documents/board'
import { boardsPageSettings } from './documents/boardsPageSettings'
import { navigation } from './documents/navigation'
import { page } from './documents/page'
import { series } from './documents/series'
import { siteSettings } from './documents/siteSettings'
import { sectionAboutPreview } from './sections/sectionAboutPreview'
import { sectionBoards } from './sections/sectionBoards'
import { sectionMarquee } from './sections/sectionMarquee'
import { sectionTextImage } from './sections/sectionTextImage'
import { sectionTextGallery } from './sections/sectionTextGallery'
import { sectionFullMedia } from './sections/sectionFullMedia'
import { sectionBigQuote } from './sections/sectionBigQuote'
import { sectionMediaLine } from './sections/sectionMediaLine'

export const schemaTypes = [accessory, accessoryCategory, accessoriesPageSettings, board, boardsPageSettings, navigation, page, series, siteSettings, sectionAboutPreview, sectionBoards, sectionMarquee, sectionTextImage, sectionTextGallery, sectionFullMedia, sectionBigQuote, sectionMediaLine]
